### ISSUE TITLE
Multiline arguments types invalid highlight

### ISSUE THREAD

**Issue by qwelias** [atom/language-typescript#32]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Multiline arguments types highlited as variables in arrow functions

### Steps to Reproduce

Type an arrow function with typed multiline arguments.

**Expected behavior:** Correct highlight

**Actual behavior:**
![Sample](https://i.imgur.com/64NME1v.png)

**Reproduces how often:** 100%

### Versions

Atom    : 1.34.0
Electron: 3.1.3
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with 1.34.0 on macOS 10.12.6 (I'm using One Dark syntax theme):

![ts-highlighting](https://github-slack.s3.amazonaws.com/monosnap/Settings__worktest-tree-sitter_2019-02-07_14-59-39.png)

Do you have Tree-sitter disabled (`Settings > Core > Enable Tree Sitter Parsers`)?

**Comment by rsese** [comment]
Ugh sorry, second time I've missed this recently :smile:

> Atom : 1.34.0
> Electron: 3.1.3

In the official stable 1.34.0 release, we're on Electron 2.0.16 - so based on your version details, we've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
