### ISSUE TITLE
update TextMate grammar

### ISSUE THREAD

**Issue by sharedprophet** [atom/language-typescript#42]
It looks like the TextMate grammar hasn't been updated since 2017...

**Comment by lkashef** [comment]
`TextMate` is no longer maintained in Atom and it's been replaced with `tree-sitter`, you can learn more about Grammar in atom at https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/.

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sharedprophet** [comment]
I am aware of Tree-Sitter but currently [semanticolor](digitallyserviced/semanticolor) cannot support Tree-Sitter grammars (see atom/atom#19151). In the meantime some of the new TypeScript syntax breaks highlighting with this TextMate grammar.

As for disregarding the template, [this](https://github.com/atom/language-typescript/blob/master/grammars/TypeScript.json#L2) wasn’t specific about how to submit an “update request” but I figured this was enough info to be considered a request for an update. Sorry about that.

**Comment by lkashef** [comment]
@sharedprophet I understand the situation but since TextMate is legacy we can no longer maintain it, also semanticolor is not an Atom Package and it's up for the author or the community to maintain it.

Although, If you are interested in updating the TextMate grammar and writing the tests, we would be happy to accept a PR, however we probably won't prioritize work on these kinds of things ourselves, as Atom has moved away from using TextMate for this language.

Thanks for understanding and meeting us half way.
